### ISSUE TITLE
Possibly Unused Function generateResponse

### ISSUE THREAD

**Issue by cammakin** [vtwireless/SAS#3]
Since there is a function in SASAlgorithms with the same name, I do not believe this function is being used anymore. 
https://github.com/vtwireless/SAS/blob/e196ba40dab1b1f1ca2e115f5632f45098ce7c13/Core/server.py#L42
It would be good to clarify this and clean up the code if this is extra.

**Comment by sauravk3** [comment]
Closing untracked issues
